const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.join(__dirname, '../../.env') });

module.exports = {
    PORT: Number(process.env.PORT || 3000),
    JWT_SECRET: process.env.JWT_SECRET || 'change-me-in-env',
    JWT_EXPIRATION: process.env.JWT_EXPIRATION || '1d',
    DB_DIALECT: process.env.DB_DIALECT || 'postgres',
    DATABASE_URL: process.env.DATABASE_URL || '',
    DB_HOST: process.env.DB_HOST || '127.0.0.1',
    DB_PORT: Number(process.env.DB_PORT || 5432),
    DB_NAME: process.env.DB_NAME || 'quantumconnects',
    DB_USER: process.env.DB_USER || 'postgres',
    DB_PASSWORD: process.env.DB_PASSWORD || 'postgres',
    DB_SSL: process.env.DB_SSL || 'false',
    DB_SSLMODE: process.env.DB_SSLMODE || '',
    DB_STORAGE: process.env.DB_STORAGE || path.join(__dirname, '../database/app.sqlite'),
    DB_LOGGING: process.env.DB_LOGGING || 'false',
    DB_SYNC_ALTER: process.env.DB_SYNC_ALTER || 'true',
    ADMIN_USERNAME: process.env.ADMIN_USERNAME || 'admin',
    ADMIN_EMAIL: process.env.ADMIN_EMAIL || 'admin@example.com',
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || 'Admin@12345',
    AUTOMATION_SHARED_KEY: process.env.AUTOMATION_SHARED_KEY || '',
    RETELL_WEBHOOK_SECRET: process.env.RETELL_WEBHOOK_SECRET || '',
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || '',
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || '',
    TWILIO_NUMBER_COUNTRY: process.env.TWILIO_NUMBER_COUNTRY || 'US',
    TWILIO_AREA_CODE: process.env.TWILIO_AREA_CODE || '',
    RETELL_API_KEY: process.env.RETELL_API_KEY || '',
    RETELL_API_BASE_URL: process.env.RETELL_API_BASE_URL || 'https://api.retellai.com',
    RETELL_CREATE_AGENT_PATH: process.env.RETELL_CREATE_AGENT_PATH || '/create-agent',
    RETELL_AGENT_TEMPLATE_ID: process.env.RETELL_AGENT_TEMPLATE_ID || '',
    RETELL_VOICE_ID: process.env.RETELL_VOICE_ID || '',
    RETELL_RESPONSE_ENGINE_TYPE: process.env.RETELL_RESPONSE_ENGINE_TYPE || 'retell-llm',
    RETELL_LLM_ID: process.env.RETELL_LLM_ID || '',
    RETELL_CONVERSATION_FLOW_ID: process.env.RETELL_CONVERSATION_FLOW_ID || '',
    RETELL_WEBHOOK_URL: process.env.RETELL_WEBHOOK_URL || '',
    RETELL_SIP_TERMINATION_URI: process.env.RETELL_SIP_TERMINATION_URI || '',
    RETELL_SIP_TRUNK_AUTH_USERNAME: process.env.RETELL_SIP_TRUNK_AUTH_USERNAME || '',
    RETELL_SIP_TRUNK_AUTH_PASSWORD: process.env.RETELL_SIP_TRUNK_AUTH_PASSWORD || '',
    OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
    OPENAI_MODEL: process.env.OPENAI_MODEL || 'gpt-4.1-mini',
    N8N_MANUAL_APPOINTMENT_WEBHOOK_URL: process.env.N8N_MANUAL_APPOINTMENT_WEBHOOK_URL || '',
    BILLING_PORTAL_URL: process.env.BILLING_PORTAL_URL || '',
    FRONTEND_APP_URL: process.env.FRONTEND_APP_URL || 'http://localhost:8080',
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || '',
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || ''
};
